# .github/workflows/build-qb64pe-win41.yml
name: Build QB64-PE v4.1 for Windows x64 (No IDE Launch)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MinGW and zip (Chocolatey)
        shell: pwsh
        run: |
          choco install mingw --version=12.2.0.03042022 -y --no-progress
          choco install zip -y --no-progress

      - name: Add MinGW to PATH
        shell: pwsh
        run: |
          $candidates = @(
            'C:\tools\mingw64\bin',                                           # common choco location
            'C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin',  # alternate choco path
            'C:\mingw64\bin'                                                  # fallback
          )
          foreach ($p in $candidates) {
            if (Test-Path $p) { $p | Out-File -FilePath $env:GITHUB_PATH -Append }
          }
          gcc --version

      - name: Clone QB64-PE source
        shell: pwsh
        run: git clone https://github.com/QB64-Phoenix-Edition/QB64pe.git qb64pe-source

      - name: Checkout version 4.1.0
        shell: pwsh
        working-directory: qb64pe-source
        run: git checkout v4.1.0

      # Run .cmd using the CMD shell; use `call` and redirect input to avoid "Press any key..."
      - name: Build QB64-PE – headless (no IDE launch)
        shell: cmd
        working-directory: qb64pe-source
        run: |
          call setup_win.cmd nolaunch < NUL

      - name: Verify binary was built
        shell: pwsh
        run: |
          if (-not (Test-Path "qb64pe-source/qb64pe.exe")) { Write-Host "qb64pe.exe missing"; exit 1 }
          Get-Item qb64pe-source/qb64pe.exe

      - name: Package for repo
        shell: pwsh
        run: |
          New-Item -ItemType Directory qb64pe_windows_x64 | Out-Null
          Copy-Item qb64pe-source/qb64pe.exe qb64pe_windows_x64/
          Copy-Item -Recurse qb64pe-source/internal qb64pe_windows_x64/
          Copy-Item qb64pe-source/Makefile qb64pe_windows_x64/
          Copy-Item -Recurse qb64pe-source/source qb64pe_windows_x64/
          Copy-Item -Recurse qb64pe-source/lib qb64pe_windows_x64/ -ErrorAction SilentlyContinue

      - name: Create zip
        shell: pwsh
        run: Compress-Archive -Path qb64pe_windows_x64 -DestinationPath qb64pe_windows_x64_v4.1.zip -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qb64pe-windows-x64-no-ide-v4.1
          path: qb64pe_windows_x64_v4.1.zip
          retention-days: 30

      - name: Job summary
        shell: pwsh
        run: |
          @'
          ## QB64-PE v4.1 Windows x64 Built (No IDE Launch)

          - Runner: **windows-2022** (has WMIC)
          - Toolchain: **MinGW-w64 12.2** via Chocolatey
          - Build script executed with **shell: cmd** using `call setup_win.cmd nolaunch`

          Download artifact: **qb64pe_windows_x64_v4.1.zip**
          '@ | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append -Encoding utf8